# Generated by Django 2.2.26 on 2022-03-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0016_party_rehearsal_dinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('da', 'Danish'), ('vt', 'Vietnamese')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='is_attending',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='party',
            name='is_attending',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(choices=[('formal', 'formal'), ('fun', 'fun')], max_length=10),
        ),
    ]
