# Generated by Django 2.2.27 on 2022-06-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20220326_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('da', 'Danish'), ('vn', 'Vietnamese')], default='en', max_length=2),
        ),
    ]
